import { useEffect, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, CalendarDays, Check, Compass, Heart, Instagram, MapPin, Menu, Mountain, Plane, Search, ShieldCheck, Sparkles, Star, Users, X } from 'lucide-react'

const photos = {
  hero: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=2200&q=88',
  bali: 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1200&q=85',
  swiss: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=85',
  kyoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=85',
  amalfi: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?auto=format&fit=crop&w=1200&q=85',
  india: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=85',
  maldives: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=85',
  escape: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=85',
  adventure: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85',
  romance: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=85',
  culture: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1200&q=85',
  journal1: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1000&q=85',
  journal2: 'https://images.unsplash.com/photo-1528360983277-13d401a686b5?auto=format&fit=crop&w=1000&q=85',
  journal3: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1000&q=85',
  cta: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=2000&q=85'
}
const destinations = [
  { name: 'Bali', country: 'INDONESIA', desc: 'Island days, your own way.', price: '₹49,999', days: '6 days', img: photos.bali, size: 'large' },
  { name: 'Swiss Alps', country: 'SWITZERLAND', desc: 'A little closer to the sky.', price: '₹89,500', days: '7 days', img: photos.swiss },
  { name: 'Kyoto', country: 'JAPAN', desc: 'Find stillness in every season.', price: '₹72,000', days: '5 days', img: photos.kyoto },
  { name: 'Amalfi Coast', country: 'ITALY', desc: 'Take the long way to the sea.', price: '₹1,19,000', days: '8 days', img: photos.amalfi, size: 'wide' },
  { name: 'Rajasthan', country: 'INDIA', desc: 'Colour, craft, and open skies.', price: '₹38,500', days: '5 days', img: photos.india },
  { name: 'Maldives', country: 'INDIAN OCEAN', desc: 'Let the days drift by.', price: '₹96,000', days: '5 days', img: photos.maldives }
]
const testimonials = [
  { quote: 'Every detail felt considered, but nothing felt over-planned. We came home with a hundred little moments we still talk about.', name: 'Ananya & Rohan', trip: 'Bali, Indonesia', initials: 'AR' },
  { quote: 'Kyoto felt like our own discovery. The local recommendations were thoughtful, and the pace was exactly what we needed.', name: 'Maya Kapoor', trip: 'Kyoto, Japan', initials: 'MK' },
  { quote: 'From the first conversation to the last train, it all felt easy. The Alps were even more beautiful than we imagined.', name: 'Ishaan Mehta', trip: 'Swiss Alps, Switzerland', initials: 'IM' }
]
const articles = [
  { category: 'SLOW TRAVEL', title: 'The art of slowing down in Bali', excerpt: 'A gentler way to meet the island, one village and one long lunch at a time.', read: '6 min read', img: photos.journal1 },
  { category: 'FIELD NOTES', title: 'A first-timer’s guide to Japan', excerpt: 'Small rituals, good train etiquette, and the pleasure of leaving room for surprise.', read: '8 min read', img: photos.journal2 },
  { category: 'LOCAL STORIES', title: 'Rajasthan, beyond the palaces', excerpt: 'Look past the grand facades to find the colour and craft of everyday life.', read: '5 min read', img: photos.journal3 }
]

function Eyebrow({ children, light = false }) { return <div className={`eyebrow ${light ? 'light' : ''}`}><span />{children}</div> }
function Navbar({ onPlan }) {
  const [scrolled, setScrolled] = useState(false), [open, setOpen] = useState(false)
  useEffect(() => { const f = () => setScrolled(window.scrollY > 36); window.addEventListener('scroll', f); return () => window.removeEventListener('scroll', f) }, [])
  const links = [['Destinations', '#destinations'], ['Experiences', '#experiences'], ['Packages', '#package'], ['Our story', '#about'], ['Journal', '#journal']]
  return <header className={`nav ${scrolled ? 'scrolled' : ''}`}><a className="brand" href="#home" aria-label="WanderVista home"><span className="brand-mark"><Compass size={20} strokeWidth={1.6}/></span><span>WanderVista<small>TRAVELS</small></span></a><nav className={open ? 'nav-links show' : 'nav-links'}>{links.map(([t, h]) => <a key={t} onClick={() => setOpen(false)} href={h}>{t}</a>)}<button className="mobile-plan" onClick={() => { setOpen(false); onPlan() }}>Plan my trip <ArrowUpRight size={15}/></button></nav><div className="nav-actions"><a className="nav-search" href="#trip-search" aria-label="Search trips"><Search size={18}/></a><button className="nav-cta" onClick={onPlan}>Plan my trip <ArrowUpRight size={15}/></button><button className="menu-btn" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></header>
}
function SearchPanel({ onSubmit }) {
 const [form, setForm] = useState({ destination: '', depart: '', returnDate: '', travelers: '2 travelers', style: 'Any style' }), [error, setError] = useState('')
 const change = e => setForm({ ...form, [e.target.name]: e.target.value })
 const submit = e => { e.preventDefault(); if (!form.destination.trim()) return setError('Choose a destination to get started.'); if (form.depart && form.returnDate && form.returnDate < form.depart) return setError('Your return date must be after your departure date.'); setError(''); onSubmit(form) }
 return <form className="search-panel" id="trip-search" onSubmit={submit}><div className="search-field destination-field"><label><MapPin size={16}/> DESTINATION</label><input name="destination" value={form.destination} onChange={change} placeholder="Where would you like to go?" list="places"/><datalist id="places">{destinations.map(d => <option key={d.name} value={d.name}/>)}</datalist></div><div className="search-field"><label><CalendarDays size={16}/> DEPARTURE</label><input name="depart" value={form.depart} onChange={change} type="date" aria-label="Departure date"/></div><div className="search-field"><label><CalendarDays size={16}/> RETURN</label><input name="returnDate" value={form.returnDate} onChange={change} type="date" aria-label="Return date"/></div><div className="search-field"><label><Users size={16}/> TRAVELERS</label><select name="travelers" value={form.travelers} onChange={change}><option>1 traveler</option><option>2 travelers</option><option>3 travelers</option><option>4 travelers</option><option>5+ travelers</option></select></div><div className="search-field"><label><Sparkles size={16}/> TRAVEL STYLE</label><select name="style" value={form.style} onChange={change}><option>Any style</option><option>Luxury escape</option><option>Adventure</option><option>Romantic getaway</option><option>Cultural journey</option></select></div><button className="search-submit" type="submit">Find my trip <ArrowUpRight size={17}/></button>{error && <p className="search-error" role="alert">{error}</p>}</form>
}
function DestinationCard({ item, index }) { return <a href="#trip-search" className={`destination-card ${item.size || ''}`} style={{ '--delay': `${index * 70}ms` }}><img src={item.img} alt={`${item.name} destination landscape`} loading="lazy"/><span className="card-shade"/><div className="destination-info"><span className="country">{item.country}</span><h3>{item.name}</h3><p>{item.desc}</p><div className="card-meta"><span>From <b>{item.price}</b></span><i/> <span>{item.days}</span><span className="circle-arrow"><ArrowUpRight size={17}/></span></div></div></a> }
function App() {
 const [result, setResult] = useState(null), [testimonial, setTestimonial] = useState(0), [email, setEmail] = useState(''), [newsletter, setNewsletter] = useState(''), [modal, setModal] = useState(false)
 const goPlan = () => { document.getElementById('trip-search')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); setTimeout(() => document.querySelector('#trip-search input[name="destination"]')?.focus(), 500) }
 const openTrip = form => { setResult(form); setModal(true) }
 const closeModal = () => setModal(false)
 useEffect(() => { document.body.style.overflow = modal ? 'hidden' : ''; const esc = e => e.key === 'Escape' && closeModal(); window.addEventListener('keydown', esc); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', esc) } }, [modal])
 const subscribe = e => { e.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { setNewsletter('Please enter a valid email address.'); return } setNewsletter('You’re on the list. Look out for a little inspiration soon.'); setEmail('') }
 return <><Navbar onPlan={goPlan}/><main>
 <section className="hero" id="home" style={{ '--hero': `url("${photos.hero}")` }}><div className="hero-inner"><Eyebrow light>TRAVEL BEYOND THE ORDINARY</Eyebrow><h1>The world is waiting.<br/><em>Go feel it.</em></h1><p>Thoughtfully curated journeys for the places you dream about and the moments you’ll remember.</p><div className="hero-buttons"><a href="#destinations" className="button button-cream">Explore destinations <ArrowUpRight size={17}/></a><button className="button button-outline" onClick={goPlan}>Create your journey <span className="play">↗</span></button></div></div><a href="#destinations" className="scroll-cue"><span><ArrowDown size={14}/></span>SCROLL TO WANDER</a><div className="hero-caption"><span>03° 08′ S &nbsp; 115° 12′ E</span><span>Bali, Indonesia</span></div></section>
 <section className="search-wrap"><SearchPanel onSubmit={openTrip}/></section>
 <section className="section destinations-section" id="destinations"><div className="section-heading"><div><Eyebrow>FIND YOUR SOMEWHERE</Eyebrow><h2>Places that <em>stay with you.</em></h2></div><div className="heading-aside"><p>From quiet coastlines to vibrant cities, discover journeys worth taking.</p><a className="text-link" href="#destinations-grid">Browse all places <ArrowUpRight size={16}/></a></div></div><div className="dest-grid" id="destinations-grid">{destinations.map((d, i) => <DestinationCard key={d.name} item={d} index={i}/>)}</div><div className="center-action"><a className="button button-dark" href="#trip-search">View all destinations <ArrowRight size={16}/></a></div></section>
 <section className="experiences-section" id="experiences"><div className="section experience-intro"><Eyebrow light>TRAVEL YOUR WAY</Eyebrow><h2>Not just trips.<br/><em>Stories to live.</em></h2><p>Every journey is different. Find the kind of experience that feels like you.</p><a className="button button-cream" href="#trip-search">Find your kind of trip <ArrowUpRight size={16}/></a></div><div className="experience-grid"><a href="#trip-search" className="experience-card exp-main"><img src={photos.escape} alt="Tropical overwater villa at sunset" loading="lazy"/><div><span>01 / UNWIND</span><h3>Luxury escapes</h3><p>Private villas, boutique hotels, and exceptional stays.</p><b>Explore experience <ArrowUpRight size={15}/></b></div></a><a href="#trip-search" className="experience-card"><img src={photos.adventure} alt="Mountain peaks in the Swiss Alps" loading="lazy"/><div><span>02 / GET OUT THERE</span><h3>Adventure trails</h3><p>Mountain escapes and wild places.</p><b>Explore experience <ArrowUpRight size={15}/></b></div></a><a href="#trip-search" className="experience-card"><img src={photos.romance} alt="Romantic dinner under the stars" loading="lazy"/><div><span>03 / JUST THE TWO OF YOU</span><h3>Romantic getaways</h3><p>Intimate stays and beautiful beginnings.</p><b>Explore experience <ArrowUpRight size={15}/></b></div></a><a href="#trip-search" className="experience-card exp-wide"><img src={photos.culture} alt="Traditional Kyoto street at dusk" loading="lazy"/><div><span>04 / GET TO KNOW A PLACE</span><h3>Cultural journeys</h3><p>Local food, architecture, and stories best told in person.</p><b>Explore experience <ArrowUpRight size={15}/></b></div></a></div></section>
 <section className="featured section" id="package"><div className="featured-image"><img src={photos.bali} alt="Palm trees overlooking the Bali coastline" loading="lazy"/><div className="image-label"><span>WANDERVISTA SELECT</span><b>01 / 06</b></div><div className="featured-stamp"><Sparkles size={16}/><span>Made for<br/>the moment</span></div></div><div className="featured-copy"><Eyebrow>THE WANDERVISTA EDIT</Eyebrow><span className="package-code">A SIGNATURE JOURNEY &nbsp; / &nbsp; INDONESIA</span><h2>Bali —<br/><em>The Island Escape</em></h2><p className="featured-desc">A little temple, a little tide, and plenty of time to simply be. Meet the island at your own pace.</p><div className="feature-tags"><span><CalendarDays size={16}/> 6 days / 5 nights</span><span><MapPin size={16}/> Bali, Indonesia</span></div><ul className="included"><li><Check size={15}/> Thoughtful private stays</li><li><Check size={15}/> Guided cultural moments</li><li><Check size={15}/> A flexible, personal itinerary</li></ul><div className="package-bottom"><div><small>JOURNEYS FROM</small><strong>₹49,999 <small>/ person</small></strong></div><button className="button button-dark" onClick={() => openTrip({ destination: 'Bali', depart: '', returnDate: '', travelers: '2 travelers', style: 'Cultural journey' })}>Explore this journey <ArrowUpRight size={16}/></button></div></div></section>
 <section className="why-section" id="about"><div className="section why-layout"><div className="why-image"><img src={photos.swiss} alt="A quiet mountain lake surrounded by alpine peaks" loading="lazy"/><div className="why-note"><span>THE WANDERVISTA WAY</span><p>Travel that feels<br/><em>like it was made for you.</em></p></div></div><div className="why-copy"><Eyebrow>MORE THAN A CHECKLIST</Eyebrow><h2>Good journeys<br/>leave room for <em>wonder.</em></h2><p>We believe the best trips have just enough plan and plenty of space to follow your curiosity. Our travel designers pair thoughtful details with the freedom to find your own way.</p><div className="values-list"><div><span><Heart size={19}/></span><div><h3>Made around you</h3><p>Your pace, your people, your version of the place.</p></div></div><div><span><Compass size={19}/></span><div><h3>Thoughtfully found</h3><p>Special stays and local moments worth travelling for.</p></div></div><div><span><ShieldCheck size={19}/></span><div><h3>Here when you need us</h3><p>A real person to help shape every step.</p></div></div></div><a className="text-link" href="#how-it-works">Get to know our approach <ArrowUpRight size={16}/></a></div></div></section>
 <section className="process-section section" id="how-it-works"><div className="process-heading"><Eyebrow>YOUR JOURNEY, WELL BEGUN</Eyebrow><h2>Four steps to <em>somewhere.</em></h2><p>From first thought to boarding pass, we make the planning feel like part of the adventure.</p></div><div className="steps"><div className="step"><div className="step-number">01 <span><MapPin size={19}/></span></div><h3>Tell us your dream</h3><p>Share where you’d love to go, when, and what makes a trip feel special.</p></div><div className="step"><div className="step-number">02 <span><Sparkles size={19}/></span></div><h3>We design your journey</h3><p>Your travel designer brings together a thoughtful first itinerary.</p></div><div className="step"><div className="step-number">03 <span><Heart size={19}/></span></div><h3>Make it yours</h3><p>Fine-tune the stays, experiences, and little details together.</p></div><div className="step"><div className="step-number">04 <span><Plane size={19}/></span></div><h3>Pack your bags</h3><p>Everything is set. All that’s left is to go feel it for yourself.</p></div></div></section>
 <section className="journal-section" id="journal"><div className="section"><div className="section-heading"><div><Eyebrow>NOTES FROM THE ROAD</Eyebrow><h2>A little inspiration for<br/>your <em>next escape.</em></h2></div><a className="text-link" href="#journal">Visit the journal <ArrowUpRight size={16}/></a></div><div className="journal-grid">{articles.map((a, i) => <article className="journal-card" key={a.title}><a className="journal-img" href="#trip-search"><img src={a.img} alt={a.title} loading="lazy"/><span>0{i + 1}</span><ArrowUpRight size={18}/></a><div className="journal-meta"><span>{a.category}</span><i/> {a.read}</div><h3><a href="#trip-search">{a.title}</a></h3><p>{a.excerpt}</p><a href="#trip-search" className="text-link">Read the story <ArrowRight size={15}/></a></article>)}</div></div></section>
 <section className="testimonial-section"><div className="section testimonial-layout"><div className="testimonial-aside"><Eyebrow>POSTCARDS FROM OUR TRAVELLERS</Eyebrow><h2>The little things<br/>make the <em>whole trip.</em></h2><p>Sample notes from the kind of journeys we love helping create.</p><div className="carousel-controls"><button aria-label="Previous testimonial" onClick={() => setTestimonial((testimonial + testimonials.length - 1) % testimonials.length)}><ArrowLeft size={17}/></button><button aria-label="Next testimonial" onClick={() => setTestimonial((testimonial + 1) % testimonials.length)}><ArrowRight size={17}/></button><span>0{testimonial + 1} <i/> 0{testimonials.length}</span></div></div><div className="quote-card"><div className="sample-label">SAMPLE TESTIMONIAL <span>DEMO BRAND</span></div><div className="stars" aria-label="Decorative sample rating">{[1,2,3,4,5].map(s => <Star size={15} fill="currentColor" key={s}/>)}</div><blockquote>“{testimonials[testimonial].quote}”</blockquote><div className="quote-author"><span className="avatar">{testimonials[testimonial].initials}</span><div><b>{testimonials[testimonial].name}</b><small>{testimonials[testimonial].trip}</small></div><span className="quote-mark">”</span></div></div></div></section>
 <section className="final-cta" style={{ '--cta': `url("${photos.cta}")` }}><div className="final-cta-inner"><Eyebrow light>THE WORLD, AT YOUR PACE</Eyebrow><h2>Your next great story<br/><em>starts here.</em></h2><p>Tell us what inspires you. We’ll help you turn it into a journey.</p><div className="hero-buttons"><button className="button button-cream" onClick={goPlan}>Plan my trip <ArrowUpRight size={17}/></button><a className="cta-secondary" href="#destinations">Explore all destinations <ArrowRight size={16}/></a></div></div><div className="final-caption">A QUIETER KIND OF GETTING AWAY &nbsp; · &nbsp; WANDERVISTA TRAVELS</div></section>
 </main><footer className="footer"><div className="footer-main"><div className="footer-brand"><a className="brand footer-logo" href="#home"><span className="brand-mark"><Compass size={20}/></span><span>WanderVista<small>TRAVELS</small></span></a><p>For the places you dream about<br/>and the moments you’ll remember.</p><div className="socials"><a href="https://instagram.com" aria-label="Instagram"><Instagram size={17}/></a><a href="https://pinterest.com" aria-label="Pinterest"><Mountain size={17}/></a></div><small className="fictional">A fictional travel brand created for demonstration.</small></div><div className="footer-links"><div><b>EXPLORE</b><a href="#destinations">Destinations</a><a href="#experiences">Experiences</a><a href="#package">Packages</a><a href="#about">About us</a><a href="#journal">Journal</a></div><div><b>HERE TO HELP</b><a href="#how-it-works">How it works</a><a href="#how-it-works">Booking information</a><a href="#how-it-works">Travel policies</a><a href="mailto:hello@wandervista.example">Contact</a></div></div><div className="newsletter"><b>A POSTCARD, NOW AND THEN</b><p>Thoughtful travel notes and a little inspiration for wherever’s next.</p><form onSubmit={subscribe}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Your email address" required/><button aria-label="Subscribe to newsletter"><ArrowRight size={17}/></button></form><p className="newsletter-feedback" aria-live="polite">{newsletter}</p></div></div><div className="footer-bottom"><span>© 2026 WanderVista Travels · Demo brand</span><div><a href="#home">Privacy</a><a href="#home">Terms</a><span>Made for the curious <span className="sun">✳</span></span></div></div></footer>
 {modal && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && closeModal()}><div className="result-modal" role="dialog" aria-modal="true" aria-labelledby="result-title"><button className="modal-close" onClick={closeModal} aria-label="Close"><X size={19}/></button><span className="modal-icon"><Check size={21}/></span><Eyebrow>YOUR JOURNEY STARTS HERE</Eyebrow><h2 id="result-title">A lovely place to <em>begin.</em></h2><p className="modal-intro">Here’s what you’re dreaming up. This is a sample trip request; no live availability has been checked.</p><div className="result-details"><div><MapPin size={17}/><span><small>DESTINATION</small><b>{result?.destination || 'Somewhere wonderful'}</b></span></div><div><CalendarDays size={17}/><span><small>DATES</small><b>{result?.depart ? `${result.depart}${result.returnDate ? ` — ${result.returnDate}` : ''}` : 'Dates to be decided'}</b></span></div><div><Users size={17}/><span><small>TRAVEL PARTY</small><b>{result?.travelers || '2 travelers'}</b></span></div><div><Sparkles size={17}/><span><small>YOUR TRAVEL STYLE</small><b>{result?.style || 'Any style'}</b></span></div></div><button className="button button-dark modal-done" onClick={() => { closeModal(); document.getElementById('trip-search')?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }}>Edit your details <ArrowRight size={16}/></button></div></div>}
 </>
}
export default App
